feeder: dataset.dataloader_video_insert_com_T_E_singleword_noshare_insertposition.BaseFeeder
#feeder: dataset.dataloader_video_insert_com_T_E_singleword_noshare_insertposition_2d.BaseFeeder


phase: train
dataset: CSL_insert_com_T_E_singleword_insertposition
# dataset: phoenix14-si5
num_epoch: 200
work_dir: /disk1/experiment_glq/20230315/NIPS_final



batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 2
device: 0
log_interval: 1000
eval_interval: 1
save_interval: 1
# python in default
evaluate_tool: sclite  #python or sclite
loss_weights:
#  ConvCTC: 1.0
  SeqCTC: 1.0
#  Dist: 25.0  ###10.0
#  cross: 1.0
#  l1: 1.0




#load_weights: /disk1/experiment_glq/20230315/NIPS/third_our_continuous_signer_new_112/third_our_continuous_signer_new_112dev_10.60_epoch49_model.pt
#load_weights: /disk1/experiment_glq/20230315/NIPS_final/different_signer_fine/different_signer_finedev_84.00_epoch0_model.pt
#load_weights: /disk1/experiment_glq/20230315/NIPS_final/signer_cte_first_new_112/signer_cte_first_new_112dev_20.10_epoch1_model.pt
#load_checkpoints: /disk1/experiment_glq/20230315/NIPS_final/different_signer_te_third1/different_signer_te_third1dev_86.10_epoch1_model.pt
#ignore_weights: ['G','D.map1','map2','D.f','D.pool','D.map3','D.adapool','D.fc']
optimizer_args:
  optimizer: Adam
  base_lr: 0.0001  #csl_daily:0.00005;
  step: [ 10, 25, 35,50]  #### original: c: [ 10, 25, 35,50]; cte: [ 1, 3, 5]; te fine-tune:[ 1, 3, 5]; c fine-tune:[ 10, 25, 35,50]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
optimizer_args_d:
  optimizer: Adam
  base_lr: 0.0001  #csl_daily:0.00005;
  step: [ 10, 25, 35,50]   ####[ 40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
#  image_scale: 1.0
  frame_interval: 2  #跑不起来
  meaningless_frame_begin: 0
  meaningless_frame_end: 0
  meaningless_frame_begin_E: 2



#model: slr_EinT_2d_new.SLRModel    # slr_insert_network_ctc_T_E_multiword_nohandframe_nosharetemporal_disentangle8_attn_contrastive_new(location) or slr_EinT
#model: slr_EinT_2d_new_SEN.SLRModel
model: slr_EinT_fine_tune.SLRModel
#model: slr_EinT_fine_tune_SEN.SLRModel

decode_mode: beam
model_args:
#  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1
#  share_classifier: True
#  weight_norm: True

